name: Survivor CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MIRROR_URL: ${{ secrets.REPO_URL }}

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install basic build
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential npm
    - name: Install Tailwind CSS
      run: |
        npm install -D tailwindcss postcss autoprefixer
    - name: Install Flowbite React
      run: |
        npm install flowbite flowbite-react

  push_to_mirror:
    needs: [Setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
